services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VITE_BACKEND_URL: ${VITE_BACKEND_URL}
                VITE_SOCKET_URL: ${VITE_SOCKET_URL}
        container_name: frontend-prod
        ports:
            - '5173:80'
        env_file:
            - .env

        restart: unless-stopped
        networks:
            - app_network
networks:
    app_network:
